export const techSkills = [
  { id: "JavaScript", name: "JavaScript" },
  { id: "TypeScript", name: "TypeScript" },
  { id: "HTML", name: "HTML" },
  { id: "CSS", name: "CSS" },
  { id: "Python", name: "Python" },
  { id: "Java", name: "Java" },
  { id: "C#", name: "C#" },
  { id: "C++", name: "C++" },
  { id: "Go", name: "Go" },
  { id: "Rust", name: "Rust" },
  { id: "Kotlin", name: "Kotlin" },
  { id: "Swift", name: "Swift" },
  { id: "SQL", name: "SQL" },
  { id: "NoSQL", name: "NoSQL" },
  { id: "Node.js", name: "Node.js" },
  { id: "React", name: "React" },
  { id: "Angular", name: "Angular" },
  { id: "Vue.js", name: "Vue.js" },
  { id: "Next.js", name: "Next.js" },
  { id: "Nuxt.js", name: "Nuxt.js" },
  { id: "Express.js", name: "Express.js" },
  { id: ".NET Core", name: ".NET Core" },
  { id: "Spring Boot", name: "Spring Boot" },
  { id: "Django", name: "Django" },
  { id: "Flask", name: "Flask" },
  { id: "Ruby on Rails", name: "Ruby on Rails" },
  { id: "PHP", name: "PHP" },
  { id: "Laravel", name: "Laravel" },
  { id: "ASP.NET", name: "ASP.NET" },
  { id: "SASS", name: "SASS" },
  { id: "LESS", name: "LESS" },
  { id: "Bootstrap", name: "Bootstrap" },
  { id: "Tailwind CSS", name: "Tailwind CSS" },
  { id: "Material UI", name: "Material UI" },
  { id: "Redux", name: "Redux" },
  { id: "NgRx", name: "NgRx" },
  { id: "RxJS", name: "RxJS" },
  { id: "Webpack", name: "Webpack" },
  { id: "Vite", name: "Vite" },
  { id: "Babel", name: "Babel" },
  { id: "Git", name: "Git" },
  { id: "GitHub", name: "GitHub" },
  { id: "GitLab", name: "GitLab" },
  { id: "Bitbucket", name: "Bitbucket" },
  { id: "CI/CD", name: "CI/CD" },
  { id: "Jenkins", name: "Jenkins" },
  { id: "Docker", name: "Docker" },
  { id: "Kubernetes", name: "Kubernetes" },
  { id: "Terraform", name: "Terraform" },
  { id: "Ansible", name: "Ansible" },
  { id: "AWS", name: "AWS" },
  { id: "Azure", name: "Azure" },
  { id: "Google Cloud Platform", name: "Google Cloud Platform" },
  { id: "Firebase", name: "Firebase" },
  { id: "Heroku", name: "Heroku" },
  { id: "Netlify", name: "Netlify" },
  { id: "MongoDB", name: "MongoDB" },
  { id: "MySQL", name: "MySQL" },
  { id: "PostgreSQL", name: "PostgreSQL" },
  { id: "SQLite", name: "SQLite" },
  { id: "Redis", name: "Redis" },
  { id: "Elasticsearch", name: "Elasticsearch" },
  { id: "GraphQL", name: "GraphQL" },
  { id: "REST API", name: "REST API" },
  { id: "SOAP", name: "SOAP" },
  { id: "Apache Kafka", name: "Apache Kafka" },
  { id: "RabbitMQ", name: "RabbitMQ" },
  { id: "Linux", name: "Linux" },
  { id: "Bash", name: "Bash" },
  { id: "PowerShell", name: "PowerShell" },
  { id: "Agile Methodologies", name: "Agile Methodologies" },
  { id: "Scrum", name: "Scrum" },
  { id: "JIRA", name: "JIRA" },
  { id: "Confluence", name: "Confluence" },
  { id: "Unit Testing", name: "Unit Testing" },
  { id: "Jest", name: "Jest" },
  { id: "Mocha", name: "Mocha" },
  { id: "Chai", name: "Chai" },
  { id: "Enzyme", name: "Enzyme" },
  { id: "Cypress", name: "Cypress" },
  { id: "Playwright", name: "Playwright" },
  { id: "Selenium", name: "Selenium" },
  { id: "Pandas", name: "Pandas" },
  { id: "NumPy", name: "NumPy" },
  { id: "Scikit-learn", name: "Scikit-learn" },
  { id: "TensorFlow", name: "TensorFlow" },
  { id: "PyTorch", name: "PyTorch" },
  { id: "Keras", name: "Keras" },
  { id: "OpenCV", name: "OpenCV" },
  { id: "Matplotlib", name: "Matplotlib" },
  { id: "Power BI", name: "Power BI" },
  { id: "Tableau", name: "Tableau" },
  { id: "Snowflake", name: "Snowflake" },
  { id: "Airflow", name: "Airflow" },
  { id: "Hadoop", name: "Hadoop" },
  { id: "Spark", name: "Spark" },
  { id: "BigQuery", name: "BigQuery" },
  { id: "Figma", name: "Figma" },
  { id: "Postman", name: "Postman" },
  { id: "Swagger", name: "Swagger" },
  { id: "OAuth", name: "OAuth" },
  { id: "JWT", name: "JWT" },
  { id: "WebSockets", name: "WebSockets" }
];
